version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
        # run build script
        - mvn clean install -DskipTests=true
        
artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - target/ccproject-0.0.1-SNAPSHOT.jar
  discard-paths: yes
